### ISSUE TITLE
Prepare unit tests for getters

### ISSUE THREAD

**Issue by MateuszJalocha** [MateuszJalocha/football_data#6]
## **TBD**

Write unit tests for getters from #5 issue

## **Tasks**

- [ ] Events getter tests
- [ ] Match Report link getter tests
- [ ] Squads getter tests
- [ ] Stats getter tests

## **Acceptance**

All tests are positive or mark as xfail with specified reason (reason need an issue)
